# Generated by Django 4.0 on 2021-12-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='repository_link',
        ),
    ]
